version: 2

models:
  - name: stg_matches_1968
    description: Model for YYYY tennis match data
    unique_key: match_num
    alias: atp_matches_year
    columns:
      - name: tourney_id
        description: Tournament ID
        tests:
          - not_null
      - name: tourney_name
        description: Tournament Name
      - name: surface
        description: Playing Surface
      - name: draw_size
        description: Draw Size
      - name: tourney_level
        description: Tournament Level
      - name: tourney_date
        description: Tournament Date
      - name: match_num
        description: Match Number
      - name: winner_id
        description: Winner's ID
      - name: winner_seed
        description: Winner's Seed
      - name: winner_entry
        description: Winner's Entry
      - name: winner_name
        description: Winner's Name
      - name: winner_hand
        description: Winner's Playing Hand
      - name: winner_ht
        description: Winner's Height
      - name: winner_ioc
        description: Winner's IOC (International Olympic Committee) Code
      - name: winner_age
        description: Winner's Age
      - name: loser_id
        description: Loser's ID
      - name: loser_seed
        description: Loser's Seed
      - name: loser_entry
        description: Loser's Entry
      - name: loser_name
        description: Loser's Name
      - name: loser_hand
        description: Loser's Playing Hand
      - name: loser_ht
        description: Loser's Height
      - name: loser_ioc
        description: Loser's IOC (International Olympic Committee) Code
      - name: loser_age
        description: Loser's Age
      - name: score
        description: Match Score
      - name: best_of
        description: Best of N Sets
      - name: round
        description: Tournament Round
      - name: minutes
        description: Match Duration (in minutes)
      - name: w_ace
        description: Number of Aces by Winner
      - name: w_df
        description: Number of Double Faults by Winner
      - name: w_svpt
        description: Number of Service Points by Winner
      - name: w_1stIn
        description: Number of First Serves In by Winner
      - name: w_1stWon
        description: Number of First Serve Points Won by Winner
      - name: w_2ndWon
        description: Number of Second Serve Points Won by Winner
      - name: w_SvGms
        description: Number of Service Games by Winner
      - name: w_bpSaved
        description: Number of Break Points Saved by Winner
      - name: w_bpFaced
        description: Number of Break Points Faced by Winner
      - name: l_ace
        description: Number of Aces by Loser
      - name: l_df
        description: Number of Double Faults by Loser
      - name: l_svpt
        description: Number of Service Points by Loser
      - name: l_1stIn
        description: Number of First Serves In by Loser
      - name: l_1stWon
        description: Number of First Serve Points Won by Loser
      - name: l_2ndWon
        description: Number of Second Serve Points Won by Loser
      - name: l_SvGms
        description: Number of Service Games by Loser
      - name: l_bpSaved
        description: Number of Break Points Saved by Loser
      - name: l_bpFaced
        description: Number of Break Points Faced by Loser
      - name: winner_rank
        description: Winner's ATP Ranking
      - name: winner_rank_points
        description: Winner's ATP Ranking Points
      - name: loser_rank
        description: Loser's ATP Ranking
      - name: loser_rank_points
        description: Loser's ATP Ranking Points
      - name: file_source
        description: Source of the ATP Matches Data (e.g., 'atp_matches_year')
